name = GitHub Dark

ghostty = GitHub Dark
wezterm = Github Dark (Gogh)
gtk     = Orchis-Grey-Dark
icons   = Colloid-Grey-Dracula-Dark

wallpaper = wallhaven-218x7m_3440x1440.png

dunst_frame_global       = #b3e5fc

dunst_bg_low             = #0a0d12
dunst_fg_low             = #b3e5fc
dunst_frame_low          = #b3e5fc
dunst_highlight_low      = #b3e5fc

dunst_bg_normal          = #0a0d12
dunst_fg_normal          = #d0d7de
dunst_frame_normal       = #b3e5fc
dunst_highlight_normal   = #39c5cf

dunst_bg_critical        = #4c2422
dunst_fg_critical        = #d0d7de
dunst_frame_critical     = #d29922
dunst_highlight_critical = #d29922
