name = Catppuccin

ghostty = Catppuccin Mocha
wezterm = Catppuccin Mocha
gtk     = Orchis-Purple-Dark
icons   = Colloid-Catppuccin-Dark

wallpaper = wallhaven-d61z1m_3440x1440.png

dunst_frame_global       = #8caaee

dunst_bg_low             = #1c1e29
dunst_fg_low             = #8caaee
dunst_frame_low          = #8caaee
dunst_highlight_low      = #8caaee

dunst_bg_normal          = #1c1e29
dunst_fg_normal          = #c6d0f5
dunst_frame_normal       = #8caaee
dunst_highlight_normal   = #b5bfe2

dunst_bg_critical        = #452727
dunst_fg_critical        = #c6d0f5
dunst_frame_critical     = #ef9f76
dunst_highlight_critical = #ef9f76
