name = Everforest

ghostty = Everforest Dark Hard
wezterm = Everforest Dark Hard (Gogh)
gtk     = Orchis-Green-Dark
icons   = Colloid-Everforest-Dark

wallpaper = wallhaven-d697og_3440x1440.png

dunst_frame_global       = #7FBBB3

dunst_bg_low             = #22282d
dunst_fg_low             = #7FBBB3
dunst_frame_low          = #7FBBB3
dunst_highlight_low      = #7FBBB3

dunst_bg_normal          = #22282d
dunst_fg_normal          = #D5C9AB
dunst_frame_normal       = #7FBBB3
dunst_highlight_normal   = #83c092

dunst_bg_critical        = #472627
dunst_fg_critical        = #D5C9AB
dunst_frame_critical     = #DBBC7F
dunst_highlight_critical = #DBBC7F
