name = Doom One

ghostty = Doom One
wezterm = DoomOne
gtk     = Orchis-Dark
icons   = Colloid-Dark

wallpaper = wallhaven-d8633m_3440x1440.png

dunst_frame_global       = #51afef

dunst_bg_low             = #202329
dunst_fg_low             = #51afef
dunst_frame_low          = #51afef
dunst_highlight_low      = #51afef

dunst_bg_normal          = #202329
dunst_fg_normal          = #bbc2cf
dunst_frame_normal       = #51afef
dunst_highlight_normal   = #c678dd

dunst_bg_critical        = #4c2020
dunst_fg_critical        = #bbc2cf
dunst_frame_critical     = #ecbe7b
dunst_highlight_critical = #ecbe7b
