name = Monokai

ghostty = Monokai Remastered
wezterm = Monokai Remastered
gtk     = Orchis-Pink-Dark
icons   = Colloid-Dark

wallpaper = wallhaven-3q9vmd_3440x1440.png

dunst_frame_global       = #66d9ef

dunst_bg_low             = #1f201b
dunst_fg_low             = #66d9ef
dunst_frame_low          = #66d9ef
dunst_highlight_low      = #66d9ef

dunst_bg_normal          = #1f201b
dunst_fg_normal          = #f8f8f2
dunst_frame_normal       = #66d9ef
dunst_highlight_normal   = #a6e22e

dunst_bg_critical        = #4a0b22
dunst_fg_critical        = #f8f8f2
dunst_frame_critical     = #f92672
dunst_highlight_critical = #f92672
