
for_window [class="^.*"] border pixel 4 
default_border pixel 4 
hide_edge_borders smart 
gaps inner 5 
gaps outer 2

#set floating window size
for_window [floating] resize set 1600 900
for_window [floating] move position center


for_window [class="qimgv"] floating enable
for_window [class="Pavucontrol"] floating enable
for_window [class="mpv"] floating enable, sticky enable
for_window [class="Lxappearance"] floating enable
for_window [class="st"] floating enable, sticky enable
for_window [class="Galculator"] floating enable, sticky enable
for_window [class="com.mitchellh.ghostty"] floating disable

# scratchpad windows
for_window [class="scratchpad"] floating enable, move scratchpad, scratchpad show, resize set 1200 800, move position center
for_window [class="Spotify"] floating enable, move scratchpad, scratchpad show, resize set 1200 800, move position center
for_window [class="pulsemixer"] floating enable, move scratchpad, scratchpad show, resize set 1000 600, move position center

