name = Moonfly

ghostty = Moonfly
wezterm = Moonfly (Gogh)
gtk     = Orchis-Dark
icons   = Colloid-Dark

wallpaper = wallhaven-x6gmxl_3440x1440.png

dunst_frame_global       = #80a0ff

dunst_bg_low             = #060606
dunst_fg_low             = #80a0ff
dunst_frame_low          = #80a0ff
dunst_highlight_low      = #80a0ff

dunst_bg_normal          = #060606
dunst_fg_normal          = #b2b2b2
dunst_frame_normal       = #80a0ff
dunst_highlight_normal   = #8cc85f

dunst_bg_critical        = #4c1919
dunst_fg_critical        = #b2b2b2
dunst_frame_critical     = #e3c78a
dunst_highlight_critical = #e3c78a
