name = Gruvbox

ghostty = Gruvbox Dark
wezterm = Gruvbox Dark (Gogh)
gtk     = Orchis-Orange-Dark
icons   = Colloid-Gruvbox-Dark

wallpaper = gruvbox-dark-debian-scalable.svg

dunst_frame_global       = #458588

dunst_bg_low             = #202020
dunst_fg_low             = #458588
dunst_frame_low          = #458588
dunst_highlight_low      = #458588

dunst_bg_normal          = #202020
dunst_fg_normal          = #ebdbb2
dunst_frame_normal       = #458588
dunst_highlight_normal   = #83a598

dunst_bg_critical        = #3d0a08
dunst_fg_critical        = #ebdbb2
dunst_frame_critical     = #d79921
dunst_highlight_critical = #d79921
