#!/bin/sh

query=$(rofi -dmenu -p "Google") || exit

url="https://www.google.com/search?q=$(python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))' "$query")"

exec ghostty -e lynx "$url"
