name = Rose Pine Moon

ghostty = Rose Pine Moon
wezterm = rose-pine-moon
gtk     = Orchis-Purple-Dark
icons   = Colloid-Catppuccin-Dark

wallpaper = wallhaven-85erok_3440x1440.png

dunst_frame_global       = #c4a7e7

dunst_bg_low             = #1c1a2b
dunst_fg_low             = #c4a7e7
dunst_frame_low          = #c4a7e7
dunst_highlight_low      = #c4a7e7

dunst_bg_normal          = #1c1a2b
dunst_fg_normal          = #e0def4
dunst_frame_normal       = #c4a7e7
dunst_highlight_normal   = #9ccfd8

dunst_bg_critical        = #46212b
dunst_fg_critical        = #e0def4
dunst_frame_critical     = #f6c177
dunst_highlight_critical = #f6c177
