name = Dracula

ghostty = Dracula
wezterm = Dracula (Official)
gtk     = Orchis-Purple-Dark-Dracula
icons   = Colloid-Dracula-Dark

wallpaper = wallhaven-ex63rk_3440x1440.png

dunst_frame_global       = #6272a4

dunst_bg_low             = #20212b
dunst_fg_low             = #6272a4
dunst_frame_low          = #6272a4
dunst_highlight_low      = #6272a4

dunst_bg_normal          = #20212b
dunst_fg_normal          = #f8f8f2
dunst_frame_normal       = #6272a4
dunst_highlight_normal   = #8be9fd

dunst_bg_critical        = #4c1919
dunst_fg_critical        = #f8f8f2
dunst_frame_critical     = #f1fa8c
dunst_highlight_critical = #f1fa8c
