name = Kanagawa

ghostty = Kanagawa Wave
wezterm = Kanagawa (Gogh)
gtk     = Orchis-Orange-Dark
icons   = Colloid-Orange-Dark

wallpaper = wallhaven-jx9mzp_3440x1440.png

dunst_frame_global       = #7e9cd8

dunst_bg_low             = #181820
dunst_fg_low             = #7e9cd8
dunst_frame_low          = #7e9cd8
dunst_highlight_low      = #7e9cd8

dunst_bg_normal          = #181820
dunst_fg_normal          = #DCD7BA
dunst_frame_normal       = #7e9cd8
dunst_highlight_normal   = #98bb6c

dunst_bg_critical        = #450a0a
dunst_fg_critical        = #DCD7BA
dunst_frame_critical     = #ff9e3b
dunst_highlight_critical = #ff9e3b
