name = Retro

ghostty = Retro
wezterm = Retro
gtk     = Orchis-Orange-Dark
icons   = Colloid-Orange-Dark

wallpaper = debdino.png

dunst_frame_global       = #FF7F00

dunst_bg_low             = #110800
dunst_fg_low             = #FF7F00
dunst_frame_low          = #FF7F00
dunst_highlight_low      = #FF7F00

dunst_bg_normal          = #110800
dunst_fg_normal          = #DE7B1B
dunst_frame_normal       = #FF7F00
dunst_highlight_normal   = #E07000

dunst_bg_critical        = #301800
dunst_fg_critical        = #DE7B1B
dunst_frame_critical     = #FF8E1F
dunst_highlight_critical = #FF8E1F
