name = Nord

ghostty = Nord
wezterm = Nord (Gogh)
gtk     = Orchis-Dark-Nord
icons   = Colloid-Nord-Dark

# wallpaper = wallhaven-6k1dj7_3440x1440.png
wallpaper = nord_mountains.png

dunst_frame_global       = #81a1c1

dunst_bg_low             = #242933
dunst_fg_low             = #81a1c1
dunst_frame_low          = #81a1c1
dunst_highlight_low      = #81a1c1

dunst_bg_normal          = #242933
dunst_fg_normal          = #d8dee9
dunst_frame_normal       = #81a1c1
dunst_highlight_normal   = #88c0d0

dunst_bg_critical        = #391d1f
dunst_fg_critical        = #d8dee9
dunst_frame_critical     = #ebcb8b
dunst_highlight_critical = #ebcb8b
